#服务端口
server:
  port: 8087

spring:
  #禁用模板缓存
  thymeleaf:
    cache: false

  #数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/campus_helper?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 20
    min-idle: 10
    max-active: 100

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

  #配置邮件
  mail:
    host: smtp.163.com
    port: 25
    username: at_tuan@163.com
    password: ZWCXOZRLCPPPZARM
    #host: smtp.qq.com
    #port: 465
    #username: 1278991950@qq.com
    #password: nimaavoborgnffji
    #protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual




#日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0